export const EVENT_DETAILS = "EVENT_DETAILS";
export const EVENT_LIST = "EVENT_LIST";
export const FEATURED_EVENT_LIST = "FEATURED_EVENT_LIST";
export const SAVED_EVENT_LIST = "SAVED_EVENT_LIST";
export const HOME = "HOME";
export const EVENT_ATTRIBUTE_FILTER = "EVENT_ATTRIBUTE_FILTER";
export const EVENT_CATEGORIES_FILTER = "EVENT_CATEGORIES_FILTER";
export const EVENT_DATE_FILTER = "EVENT_DATE_FILTER";
export const PARADE = "PARADE";
export const SUPPORT_US = "SUPPORT_US";
export const DONATE = "DONATE";
export const SPONSOR = "SPONSOR";
export const PARADE_INFORMATION = "PARADE_INFORMATION";
export const PARADE_MAP = "PARADE_MAP";

export const routesWithoutEvents = [PARADE, DONATE, SPONSOR, SUPPORT_US];
