puts "Running fastlane to generate and upload an ipa file..."

options = {
  xcodebuild: {
    project: "PrideLondonApp.xcworkspace"
  }
}

require 'fastlane'
result = Fastlane::OneOff.run(action: "build_and_upload_to_appetize",
                          parameters: options)

device_grid.run(
  public_key: result,
  devices: ["iphone5s", "iphone6splus", "ipadair"]
)