fastlane_version "2.67.0"

default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "PrideLondonApp")
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    # fetch previously generated certificates, but don't generate new ones if none already exist
    match(type: "appstore", readonly: true)
    # ensure we're on the "master" git branch
    ensure_git_branch(branch: "deploy-ios")
    # set the app build number from our previously generated config
    increment_build_number()
    # set the app version from our previously generated config
    # increment_version_number()
    # build the app for app store export
    gym(
      clean: true,
      export_method: 'app-store',
      scheme: "PrideLondonApp",
      output_directory: "./build-tools/deploy/data"
    )
    # upload to TestFlight and notify testers
    # testflight(
    #  skip_submission: true
    #)
  end
end