fastlane_version "2.81.0"

default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "PrideLondonApp")
  end

  desc "Signed build"
  lane :build do
    match(type: "appstore", readonly: true)
    gym(
      clean: true,
      export_method: "app-store",
      scheme: "PrideLondonApp"
    )
  end

  desc "Alpha build and deploy"
  lane :alpha do |options|
    build
    if options[:submit]
      deploy_hockey(options: options)
    end
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    ensure_git_branch(branch: "master")
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "PrideLondonApp.xcodeproj"
    )
    build
    testflight  
  end

  desc "Upload to TestFlight and notify testers"
  lane :testflight do
    testflight(
      skip_submission: true,
      distribute_external: false,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Upload to HockeyApp and notify testers"
  lane :deploy_hockey do |options|
    hockey(
      api_token: options[:api_token],
      public_identifier: options[:app_id],
      notes: notes,
      status: options[:status],
      notify: options[:notify],
      commit_sha: options[:commit_sha]
    )
  end
end