fastlane_version "2.82.0"

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build application"
  lane :build_beta do
    gradle(
      task: 'assemble',
      build_type: 'Release',
      flavor: "beta",
    )
  end

  desc "Build alpha"
  lane :build_alpha do
    gradle(
      task: "assemble",
      build_type: "release",
      flavor: "alpha",
    )
  end

  desc "Build and deploy to Alpha lane"
  lane :alpha do |options|
    build_alpha
    if options[:submit]
      apk_path = "./app/build/outputs/apk/app-alpha-release.apk"
      deploy_hockey(
        commit_sha: options[:commit_sha],
        api_token: options[:api_token],
        app_id: options[:app_id],
        apk_path: apk_path,
        status: "2",
        notify: "0",
      )
    end
  end

  desc "Build and deploy to Beta lane"
  lane :beta do |options|
    build_beta
    if options[:submit]
      apk_path = "./app/build/outputs/apk/app-beta-release.apk"
      deploy_hockey(
        commit_sha: options[:commit_sha],
        api_token: options[:api_token],
        app_id: options[:app_id],
        apk_path: apk_path,
        status: "2",
        notify: "1",
      )
    end
  end

  desc "Deploy to HockeyApp"
  lane :deploy_hockey do |options|
    notes = sh("git log --format=%B -n 1 #{options[:commit_sha]}")
    hockey(
      api_token: options[:api_token],
      public_identifier: options[:app_id],
      apk: options[:apk_path],
      notes: notes,
      status: options[:status],
      notify: options[:notify],
      commit_sha: options[:commit_sha]
    )
  end
end