fastlane_version "2.81.0"

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build application"
  lane :build do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
  end

  desc "Build application"
  lane :alpha do |options|
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    if options[:submit]
      hockey(
        api_token: options[:api_token],
        public_identifier: options[:app_id],
        ipa: options[:ipa],
        notes: options[:notes],
        status: options[:status],
        notify: options[:notify],
        commit_sha: options[:commit_sha]
      )
    end
  end
end